repos:
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: ["--settings-path=pyproject.toml"] # https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.24.0
    hooks:
      - id: commitizen
        stages: [commit-msg]